# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('user_name', models.CharField(default='\u533f\u540d', max_length=20)),
                ('kind', models.CharField(choices=[('Python\u6280\u672f', 'Python\u6280\u672f'), ('\u6570\u636e\u5e93\u6280\u672f', '\u6570\u636e\u5e93\u6280\u672f'), ('\u7ecf\u6d4e\u5b66', '\u7ecf\u6d4e\u5b66'), ('\u6587\u4f53\u8d44\u8baf', '\u6587\u4f53\u8d44\u8baf'), ('\u4e2a\u4eba\u5fc3\u60c5', '\u4e2a\u4eba\u5fc3\u60c5'), ('\u5176\u4ed6', '\u5176\u4ed6')], default=('Python\u6280\u672f', 'Python\u6280\u672f'), max_length=20)),
            ],
        ),
    ]
